### PR TITLE
Pass R CMD check

### PR DESCRIPTION
**Pull request by hadley**
First PR :)

### CODE REVIEW

**Comment by hadley** [comment]
Any comments? This should be the minimal set of changes needed to fix the existing ERRORs and WARNNGs.

**Comment by tdhock** [comment]
Thanks for the contributions. Can you please provide a test for the functionality that you expect? or is that too complicated to test since you are interested in the situation where the package is not attached?

**Comment by hadley** [comment]
This doesn't do anything new except pass R CMD check cleanly.

**Comment by hadley** [comment]
I've taken over maintenance of proto, forked it, and fixed the problems that required it to be imported. This fixes #3.  I don't think there's any easy way to test this stuff - generally if R CMD check passes with no NOTEs (and upstream packages have correctly configured namespaces) everything should just work.

**Comment by tdhock** [comment]
what about this test? (for example we could put it in tests/unattached.R, not using testthat)

```r
library(ggplot2)
no.labels <- ggplot(iris, aes(Petal.Length, Petal.Width, color=Species))+
  geom_point()
with.labels <- no.labels+
  directlabels::geom_dl(aes(label=Species), method="smart.grid")
print(with.labels)
```

using my master code I got an error:

```
> print(with.labels)
Error: could not find function "dlgrob"
```

and using your fork I also got an error, but actually earlier:

```
> with.labels <- no.labels+
+   directlabels::geom_dl(aes(label=Species), method="smart.grid")
Error in directlabels::geom_dl(aes(label = Species), method = "smart.grid") : 
  attempt to apply non-function
```

**Comment by tdhock** [comment]
and actually I get that error with your fork even after attaching directlabels.

**Comment by hadley** [comment]
Do you have the dev version of proto?

**Comment by tdhock** [comment]
after doing `devtools::install_github("hadley/proto")` I got

```
> library(ggplot2)
> no.labels <- ggplot(iris, aes(Petal.Length, Petal.Width, color=Species))+
+   geom_point()
> with.labels <- no.labels+
+   directlabels::geom_dl(aes(label=Species), method="smart.grid")
> print(with.labels)
Error: could not find function "dlgrob"
> library(directlabels)
> print(with.labels)
> 
```

**Comment by hadley** [comment]
Oh hmmm, seeing it now. I'lll take a look.

**Comment by hadley** [comment]
Oh this is a design problem with proto. GeomDirectLabel inherits from ggplot2:::Geom, so the its search path includes ggplot2, not directlabels.  Take a look at my most recent push

**Comment by tdhock** [comment]
that works for me.

before I merge can you please update the NEWS file, set the Version to the current date, and add this more robust test?

```
if("package:directlabels" %in% search()){
  detach(package:directlabels)
}
library(ggplot2)
no.labels <- ggplot(iris, aes(Petal.Length, Petal.Width, color=Species))+
  geom_point()
with.labels <- no.labels+
  directlabels::geom_dl(aes(label=Species), method="smart.grid")
print(with.labels)
```

**Comment by hadley** [comment]
That test seems rather risky to me - in general detaching a package is not reliable, and doing it in the middle of R CMD check (which may assume that the package is loaded) seems particularly dangerous.

**Comment by tdhock** [comment]
that test fails for my current master but passes for your fork, so what more could we ask for? in what sense is it dangerous or unreliable to detach the package?

**Comment by hadley** [comment]
In the sense of the documentation: "If a package has a namespace, detaching it does not by default unload the namespace (and may not even with unload = TRUE), and detaching will not in general unload any dynamically loaded compiled code (DLLs). Further, registered S3 methods from the namespace will not be removed."

...

"So detaching and re-attaching a package may not refresh some or all components of the package, and is inadvisable."

In my opinion it is a bad idea, but it's your package, so I'll bow to your judgement.

**Comment by tdhock** [comment]
thanks for the code contributions and explanations!

**Pull request merged**
